#!/usr/bin/env python
import os
import sys
import yaml
import requests
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('path')
parser.add_argument('remote')
parser.add_argument('version')

args = parser.parse_args()

with open('list.repos', 'r') as f:
    data = yaml.load(f.read(), Loader=yaml.BaseLoader)

resp = requests.get('https://github.com/{}.git'.format(args.remote))

if resp.status_code != 200:
  print('Unknown repository')

data['repositories']['resources/{}'.format(args.path)] = {
  'url': 'https://github.com/{}.git'.format(args.remote), 
  'version': args.version,
  'type': 'git'
}

with open('list.repos', 'w') as f:
  f.write(yaml.safe_dump(data))
