# This is a basic workflow to help you get started with Actions

name: Generate Documentation

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      remote:
        description: 'Remote repository to import/build'
        required: true
      path:
        description: 'The location in the resources heirarchy to add the remote repository'
        required: true
      commit:
        description: 'The branch/commit to import/build'
        required: false
        default: master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Runs a single command using the runners shell
    - name: Setup environment
      run: |
        git config --global user.email "g.suddrey@qut.edu.au"
        git config --global user.name "Gavin Suddrey"

    - name: Pull Documentation
      run: git clone https://${{secrets.USERNAME}}:${{secrets.API_KEY}}@github.com/suddrey-qut/suddrey-qut.github.io.git

    - name: Prepare resources
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
        if [ "${{ github.event.inputs.path }}" != "" ]; then \
          ./init-repo ${{ github.event.inputs.path }} ${{ github.event.inputs.remote }} ${{ github.event.inputs.commit }}; \
        fi
        vcs import < list.repos
        ./setup

    - name: Build Documentation
      run: mkdocs build -d site/docs/
    
    # Runs a set of commands using the runners shell
    - name: Push Documentation
      run: |
        git add . && git commit -m 'Automatically generated update' && git push
